sudo: false
dist: trusty
language: node_js
node_js:
  - '9.0'

cache:
  directories:
    - node_modules

notifications:
    email: true
    irc:
        channels:
            - "chat.freenode.net#projectci"
        on_success: always
        on_failure: always

before_script:
- npm install -g angular-cli
- npm install

script: ng build
